services/DeviceAdministration/Web/Controllers/DeviceMethodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Exceptions;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Models;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Models.Commands;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure.BusinessLogic;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Security;
using Newtonsoft.Json;

namespace Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Controllers
{
    [Authorize]
    [OutputCache(CacheProfile = "NoCacheProfile")]
    public class DeviceMethodController : Controller
    {
        private static readonly List<string> PrivateCommands = new List<string>
        {
            // currently there are no commands which need to be hidden in the
            // generic command view (like change device key, etc)
        };

        private readonly IDeviceLogic _deviceLogic;
        private readonly ICommandParameterTypeLogic _commandParameterTypeLogic;

        public DeviceMethodController(IDeviceLogic deviceLogic, ICommandParameterTypeLogic commandParameterTypeLogic)
        {
            _deviceLogic = deviceLogic;
            _commandParameterTypeLogic = commandParameterTypeLogic;
        }

        [RequirePermission(Permission.ViewDevices)]
        public async Task<ActionResult> Index(string deviceId)
        {
            DeviceModel device = await _deviceLogic.GetDeviceAsync(deviceId);
            if (device.DeviceProperties == null)
            {
                throw new DeviceRequiredPropertyNotFoundException("'DeviceProperties' property is missing");
            }
           
            IList<SelectListItem> commandListItems = MethodListItems(device);

            bool deviceIsEnabled = device.DeviceProperties.GetHubEnabledState();

            DeviceCommandModel deviceCommandsModel = new DeviceCommandModel
            {
                CommandHistory = device.CommandHistory.Where(c => c.DeliveryType == DeliveryType.Method).ToList(),
                CommandsJson = JsonConvert.SerializeObject(device.Commands.Where(c => c.DeliveryType == DeliveryType.Method)),
                SendCommandModel = new SendCommandModel
                {
                    DeviceId = device.DeviceProperties.DeviceID,
                    CommandSelectList = commandListItems,
                    CanSendDeviceCommands = deviceIsEnabled && PermsChecker.HasPermission(Permission.SendCommandToDevices)
                },
                DeviceId = device.DeviceProperties.DeviceID
            };

            return View(deviceCommandsModel);
        }

        [HttpPost]
        [RequirePermission(Permission.SendCommandToDevices)]
        [ValidateAntiForgeryToken]
        public ActionResult Method(string deviceId, Command command)
        {
            var model = new CommandModel
            {
                DeviceId = deviceId,
                Name = command.Name,
                DeliveryType = command.DeliveryType,
                Parameters = command.Parameters.ToParametersModel().ToList(),
                Description = command.Description
            };
            return PartialView("_InvokeMethodForm", model);
        }

        [HttpPost]
        [RequirePermission(Permission.SendCommandToDevices)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> InvokeMethod(CommandModel model)
        {
            if (ModelState.IsValid)
            {
                IDictionary<String, Object> parameters = new Dictionary<string, object>();

                if (model.Parameters != null)
                {
                    foreach (var parameter in model.Parameters)
                    {
                        parameters.Add(new KeyValuePair<string, object>(parameter.Name,
                            _commandParameterTypeLogic.Get(parameter.Type, parameter.Value)));
                    }
                }

                await _deviceLogic.SendCommandAsync(model.DeviceId, model.Name, model.DeliveryType, parameters);
 
                return Json(new {data = model});
            }

            return PartialView("_InvokeMethodForm", model);
        }

        [HttpPost]
        [RequirePermission(Permission.SendCommandToDevices)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ReinvokeMethod(string deviceId, string name, DeliveryType deliveryType, string commandJson)
        {
            try
            {
                IDictionary<string, object> commandParameters = JsonConvert.DeserializeObject<Dictionary<string, object>>(commandJson);

                await _deviceLogic.SendCommandAsync(deviceId, name, deliveryType, commandParameters);
            }
            catch
            {
                return Json(new {error = "Failed to send device"});
            }


            return Json(new { wasSent = true });
        }

        private IList<SelectListItem> MethodListItems(DeviceModel device)
        {
            if (device.Commands != null)
            {
                return GetMethodListItems(device);
            }

            return new List<SelectListItem>();
        }


        private IList<SelectListItem> GetMethodListItems(DeviceModel device)
        {
            IList<SelectListItem> result = new List<SelectListItem>();
            IList<Command> commands = device.Commands;

            if (commands != null)
            {
                foreach (Command command in commands)
                {
                    if (IsCommandPublic(command) && command.DeliveryType == DeliveryType.Method)
                    {
                        SelectListItem item = new SelectListItem();
                        item.Value = command.Name;
                        item.Text = command.Name;
                        result.Add(item);
                    }
                }
            }

            return result;
        }

        private static bool IsCommandPublic(Command command)
        {
            if (command == null)
            {
                throw new ArgumentNullException("command");
            }

            if (command.Name == null)
            {
                throw new DeviceRequiredPropertyNotFoundException("'Name' property on command not found");
            }

            return !PrivateCommands.Contains(command.Name.ToString());
        }
    }
}

services/DeviceAdministration/Web/Views/DeviceMethod/Index.cshtml
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Helpers
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Helpers
@using GlobalResources
@using Newtonsoft.Json
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.DeviceCommandModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutNoNavigation.cshtml";

    DateTime? resolvedTime;

    bool canSendCommands =
        Model.SupportDeviceCommand &&
        (Model.SendCommandModel != null) &&
        Model.SendCommandModel.CanSendDeviceCommands;
}

<header class="header_main">

    <button class="header_main__button_back" type="button"></button>
    <h2 class="header_main__subhead header_main__subhead--large">@string.Format(Strings.DeviceMethodsHeader, Model.DeviceId)</h2>

</header>

<div class="content_outer content_outer--inherit_overflow">

    <div class="content_inner">
        @if (Model.SupportDeviceCommand)
        {
            Html.RenderPartial("_InvokeMethod", Model.SendCommandModel);
        }

        <div class="command_container display_none" id="content">

            <h3>@Strings.MethodHistory</h3>

            <table id="commandHistory">
                <thead>
                    <tr>
                        <th>@Strings.MethodName</th>
                        <th>@Strings.CommandResult</th>
                        <th>@Strings.CommandValuesSent</th>
                        <th>@Strings.CommandValuesReturned</th>
                        <th>@Strings.CommandTimeCreated</th>
                        <th>@Strings.CommandTimeUpdated</th>
                        @if (canSendCommands)
                        {
                            <th></th>
                        }

                    </tr>
                </thead>
                <tbody>
                    @{
                        var supportedCommandNames = DeviceDisplayHelper.BuildAvailableCommandNameSet(Model);
                    }
                    @foreach (var commandHistoryItem in Model.CommandHistory)
                    {
                        <tr>
                            <td>
                                @commandHistoryItem.Name
                            </td>
                            <td>
                                @{string result = commandHistoryItem.Result;}
                                @{string errorMessage = commandHistoryItem.ErrorMessage;}
                                @(Html.Partial("_MethodResult", result ?? Strings.Pending, new ViewDataDictionary {{"ErrorMessage", errorMessage}}))
                            </td>
                            <td>
                                @DynamicValuesHelper.ConvertToJsonString(commandHistoryItem.Parameters)
                            </td>
                            <td>
                                @commandHistoryItem.ReturnValue
                            </td>
                            <td>
                                @{ resolvedTime = DynamicValuesHelper.ConvertToDateTime(commandHistoryItem.CreatedTime); }
                                @Html.DisplayFor(m => resolvedTime)
                            </td>
                            <td>
                                @{ resolvedTime = DynamicValuesHelper.ConvertToDateTime(commandHistoryItem.UpdatedTime); }
                                @if (resolvedTime.HasValue)
                                {
                                    @Html.DisplayFor(m => resolvedTime)
                                }
                                else
                                {
                                    @Strings.Pending
                                }

                            </td>
                            @if (canSendCommands)
                            {
                                <td>
                                    @{
                                    string commandName = commandHistoryItem.Name;
                                    if (!string.IsNullOrWhiteSpace(commandName) && supportedCommandNames.Contains(commandName))
                                    {
                                        <button class="button_base resend_command"
                                                data-command-name="@commandName"
                                                data-command-deliverytype="@commandHistoryItem.DeliveryType"
                                                data-command-json="@commandHistoryItem.GetParameterString()">
                                            @Strings.Reinvoke
                                        </button>
                                    }
                                    }
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        "use strict";

        var resources = {
            redirectToIndexUrl: '@Url.Action("Index", "Device")',
            commands: '@Html.JavaScriptString(@Model.CommandsJson)',
            deviceId: '@Model.DeviceId',
            deviceIsEnabled: '@Model.DeviceIsEnabled.ToString().ToLower()',
            commandError: '@Html.JavaScriptString(Strings.MethodError)',
            commandSendError: '@Html.JavaScriptString(Strings.MethodCallError)',
            resendCommandError: '@Html.JavaScriptString(Strings.ReinvokeMethodError)',
            sortColumnIndex: 4,
            commandUI: '/DeviceMethod/Method',
            resendCommand: '/DeviceMethod/ReinvokeMethod'
        }
    </script>

    <script type="text/javascript" src="~/Scripts/jquery-dataTables-plugins.js"></script>
    <script type="text/javascript" src="~/Scripts/Views/DeviceCommand/DeviceCommandIndex.js?ver=@Constants.JSVersion"></script>
}

services/DeviceAdministration/Web/Views/DeviceMethod/_InvokeMethod.cshtml
@using System.Web.Mvc.Html
@using GlobalResources
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.SendCommandModel

@if (Model.CanSendDeviceCommands)
{

    if (Model.HasCommands)
    {
        <fieldset class="command_form">
            <div class="tooltip_header non_float">
                @Html.LabelFor(m => m.Command, Strings.Method, new { @class = "command_form__label" })
                <img src="~/Content/img/icon_info_gray.svg" class="details_grid_info tooltip_icon" style="top:10px;" title="@Strings.MethodHeader" />
            </div>
            @Html.DropDownListFor(m => Model.Command, Model.CommandSelectList, Strings.SelectAMethod, new { @class = "command_form__select" })
            @Html.ValidationMessageFor(model => model.Command)
            @Html.AntiForgeryToken()
            <div id="command_form" class="container_command"></div>
        </fieldset>
    }
    else
    {
        <fieldset>
            <h3>@string.Format(Strings.NoMethodsAvailable, Model.DeviceId)</h3>
        </fieldset>
    }
}
else
{
    <fieldset>
        <h3>@string.Format(Strings.DeviceMethodIsDisabled)</h3>
    </fieldset>
}

services/DeviceAdministration/Web/Views/DeviceMethod/_InvokeMethodForm.cshtml
@using GlobalResources
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Models.Commands
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.CommandModel

@using (Ajax.BeginForm("InvokeMethod", "DeviceMethod", null,
        new AjaxOptions()
        {
            HttpMethod = "POST",
            OnBegin = "IoTApp.DeviceCommand.onBegin",
            OnFailure = "IoTApp.DeviceCommand.onFailure",
            OnSuccess = "IoTApp.DeviceCommand.onSuccess",
            OnComplete = "IoTApp.DeviceCommand.onComplete",
            LoadingElementId = "loadingElement",

        }, null))
{
    @Html.AntiForgeryToken()
    <p class="command_description">@Model.Description</p>
    for (var i = 0; i < Model.Parameters.Count; i++)
    {
        <div class="command_parameter_field">
            @Html.LabelFor(m => m.Parameters[i].Name, Model.Parameters[i].Name, new { @class = "command_parameter_field__label" })
            @Html.EditorFor(m => m.Parameters[i].Value, string.Format("edit_{0}", Model.Parameters[i].Type), new { Suffix = string.Format("Value_{0}", i) })
            @Html.ValidationMessageFor(m => m.Parameters[i].Value)
            @foreach (var message in Model.Parameters[i].ErrorMessages)
            {
                @IoTHelpers.ErrorLabel(message);
            }
            @Html.HiddenFor(model => Model.Parameters[i].Name)
            @Html.HiddenFor(model => Model.Parameters[i].Type)
        </div>

    }

    @Html.HiddenFor(command => command.Name)
    @Html.HiddenFor(command => command.DeviceId)
    @Html.HiddenFor(command => command.DeliveryType)
    <button type="submit" id="sendCommand_button" class="button_base button_execute">@Strings.InvokeMethod</button>
}

services/DeviceAdministration/Web/Views/DeviceMethod/_MethodResult.cshtml
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Helpers
@using GlobalResources
@model string
@{
    var separator = string.Empty;

    var localizedResults = 
        DeviceDisplayHelper.GetLocalizedCommandResultText(
            Model, 
            ViewData["ErrorMessage"]);

    var className = DeviceDisplayHelper.GetCommandResultClassName(Model);

    if (!string.IsNullOrEmpty(localizedResults.Value))
    {
        separator = ":";
    }

    <span class="@className.ToLowerInvariant()">@string.Format("{0}{1}", localizedResults.Key, separator)</span>
}

@if (!string.IsNullOrEmpty(separator))
{
    <span class="command_history__error_message" data-error-message="@localizedResults.Value">@Strings.ClickToDisplayError</span>
}