services/DeviceAdministration/Web/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using DeviceManagement.Infrustructure.Connectivity.Exceptions;
using DeviceManagement.Infrustructure.Connectivity.Models.TerminalDevice;
using GlobalResources;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Configurations;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Exceptions;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Factory;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Helpers;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Models;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure.BusinessLogic;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure.Exceptions;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure.Models;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure.Repository;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Helpers;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Security;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Controllers
{
    [Authorize]
    [OutputCache(CacheProfile = "NoCacheProfile")]
    public class DeviceController : Controller
    {
        private readonly IDeviceLogic _deviceLogic;
        private readonly IDeviceTypeLogic _deviceTypeLogic;
        private readonly IApiRegistrationRepository _apiRegistrationRepository;
        private readonly ICellularExtensions _cellularExtensions;
        private readonly IJobRepository _jobRepository;
        private readonly IUserSettingsLogic _userSettingsLogic;
        private readonly IIoTHubDeviceManager _deviceManager;
        private readonly IDeviceIconRepository _iconRepository;
        private readonly string _iotHubName;

        public DeviceController(IDeviceLogic deviceLogic,
            IDeviceTypeLogic deviceTypeLogic,
            IConfigurationProvider configProvider,
            IApiRegistrationRepository apiRegistrationRepository,
            ICellularExtensions cellularExtensions,
            IJobRepository jobRepository,
            IUserSettingsLogic userSettingsLogic,
            IIoTHubDeviceManager deviceManager,
            IDeviceIconRepository iconRepository)
        {
            _deviceLogic = deviceLogic;
            _deviceTypeLogic = deviceTypeLogic;
            _apiRegistrationRepository = apiRegistrationRepository;
            _cellularExtensions = cellularExtensions;
            _jobRepository = jobRepository;
            _userSettingsLogic = userSettingsLogic;
            _deviceManager = deviceManager;
            _iconRepository = iconRepository;

            _iotHubName = configProvider.GetConfigurationSettingValue("iotHub.HostName");
        }

        [RequirePermission(Permission.ViewDevices)]
        public async Task<ActionResult> Index(string filterId)
        {
            ViewBag.FilterId = filterId;
            ViewBag.HasManageJobsPerm = PermsChecker.HasPermission(Permission.ManageJobs);
            ViewBag.HasDeleteSuggestedClausePerm = PermsChecker.HasPermission(Permission.DeleteSuggestedClauses);
            ViewBag.IconBaseUrl = await _iconRepository.GetIconStorageUriPrefix();
            ViewBag.IconTagName = Constants.DeviceIconTagName;

            return View();
        }

        [RequirePermission(Permission.AddDevices)]
        public async Task<ActionResult> AddDevice()
        {
            var deviceTypes = await _deviceTypeLogic.GetAllDeviceTypesAsync();
            return View(deviceTypes);
        }

        [RequirePermission(Permission.AddDevices)]
        public async Task<ActionResult> SelectType(DeviceType deviceType)
        {
            if (_apiRegistrationRepository.IsApiRegisteredInAzure())
            {
                try
                {
                    var registrationModel = _apiRegistrationRepository.RecieveDetails();
                    List<DeviceModel> devices = await GetDevices();
                    ViewBag.AvailableIccids = _cellularExtensions.GetListOfAvailableIccids(devices,
                        registrationModel.ApiRegistrationProvider);
                    ViewBag.CanHaveIccid = true;
                }
                catch (CellularConnectivityException)
                {
                    ViewBag.CanHaveIccid = false;
                }
            }
            else
            {
                ViewBag.CanHaveIccid = false;
            }

            // device type logic getdevicetypeasync
            var device = new UnregisteredDeviceModel
            {
                DeviceType = deviceType,
                IsDeviceIdSystemGenerated = true
            };
            return PartialView("_AddDeviceCreate", device);
        }

        [HttpPost]
        [RequirePermission(Permission.AddDevices)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddDeviceCreate(string button, UnregisteredDeviceModel model)
        {
            bool isModelValid = ModelState.IsValid;
            bool onlyValidating = (button != null && button.ToLower().Trim() == "check");

            if (ReferenceEquals(null, model) ||
                (model.GetType() == typeof(object)))
            {
                model = new UnregisteredDeviceModel();
            }

            if (_apiRegistrationRepository.IsApiRegisteredInAzure())
            {
                try
                {
                    var registrationModel = _apiRegistrationRepository.RecieveDetails();
                    List<DeviceModel> devices = await GetDevices();
                    ViewBag.AvailableIccids = _cellularExtensions.GetListOfAvailableIccids(devices,
                        registrationModel.ApiRegistrationProvider);
                    ViewBag.CanHaveIccid = true;
                }
                catch (CellularConnectivityException)
                {
                    ViewBag.CanHaveIccid = false;
                }
            }
            else
            {
                ViewBag.CanHaveIccid = false;
            }

            //reset flag
            model.IsDeviceIdUnique = false;

            if (model.IsDeviceIdSystemGenerated)
            {
                //clear the model state of errors prior to modifying the model
                ModelState.Clear();

                //assign a system generated device Id
                while (true)
                {
                    var random = BitConverter.ToUInt32(Guid.NewGuid().ToByteArray(), 0);
                    string deviceId = $"CoolingSampleDevice_{random % 10000:d4}";

                    if (!await GetDeviceExistsAsync(deviceId))
                    {
                        model.DeviceId = deviceId;
                        break;
                    }
                }

                //validate the model
                isModelValid = TryValidateModel(model);
            }

            if (isModelValid)
            {
                bool deviceExists = !model.IsDeviceIdSystemGenerated && await GetDeviceExistsAsync(model.DeviceId);

                model.IsDeviceIdUnique = !deviceExists;

                if (model.IsDeviceIdUnique)
                {
                    if (!onlyValidating)
                    {
                        return await Add(model);
                    }
                }
                else
                {
                    ModelState.AddModelError("DeviceId", Strings.DeviceIdInUse);
                }
            }

            return PartialView("_AddDeviceCreate", model);
        }

        [HttpPost]
        [RequirePermission(Permission.AddDevices)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditDeviceProperties(EditDevicePropertiesModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    return await Edit(model);
                }
                catch (ValidationException exception)
                {
                    if (exception.Errors != null && exception.Errors.Any())
                    {
                        exception.Errors.ToList<string>().ForEach(error => ModelState.AddModelError(string.Empty, error));
                    }
                }
                catch (Exception)
                {
                    ModelState.AddModelError(string.Empty, Strings.DeviceUpdateError);
                }
            }

            return View("EditDeviceProperties", model);
        }

        private async Task<ActionResult> Add(UnregisteredDeviceModel model)
        {
            var deviceWithKeys = await AddDeviceAsync(model);
            var newDevice = new RegisteredDeviceModel
            {
                HostName = _iotHubName,
                DeviceType = model.DeviceType,
                DeviceId = deviceWithKeys.Device.DeviceProperties.DeviceID,
                PrimaryKey = deviceWithKeys.SecurityKeys.PrimaryKey,
                SecondaryKey = deviceWithKeys.SecurityKeys.SecondaryKey,
                InstructionsUrl = model.DeviceType.InstructionsUrl
            };

            return PartialView("_AddDeviceCopy", newDevice);
        }

        [RequirePermission(Permission.EditDeviceMetadata)]
        public async Task<ActionResult> EditDeviceProperties(string deviceId)
        {
            EditDevicePropertiesModel model;
            IEnumerable<DevicePropertyValueModel> propValModels;

            model = new EditDevicePropertiesModel
            {
                DevicePropertyValueModels = new List<DevicePropertyValueModel>()
            };

services/DeviceAdministration/Web/Views/Device/AddDevice.cshtml
@using GlobalResources
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Helpers
@{
    ViewBag.Title = "Add a Device";
}

<header class="header_main">

    <h1 class="header_main__head">@Strings.AddDevice</h1>
    <button class="header_main__button_back" type="button"></button>
    <h2 class="header_main__subhead">@Strings.StepOneHeader</h2>

</header>
<div class="content_outer">

    <div class="content_inner">
        <div id="content">
            @Html.Partial("_AddDeviceSelectType")
        </div>
    </div>
</div>

@*The scripts below runs when the view loads but not for partials.*@
<script type="text/javascript">
    "use strict";

    var addDeviceResources = {
        addDevice: '@Html.JavaScriptString(Strings.AddDevice)',
        stepOneHeader: '@Html.JavaScriptString(Strings.StepOneHeader)',
        redirectToIndexUrl: '@Url.Action("Index", "Device")',
        deviceDetailDeviceId: '@ViewBag.DeviceId'
    }

    $.extend(resources, addDeviceResources);
</script>

<script type="text/javascript" src="~/Scripts/Views/Device/AddDevice.js?ver=@Constants.JSVersion"></script>

services/DeviceAdministration/Web/Views/Device/EditDesiredProperties.cshtml
@using System.Globalization
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Helpers
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure.Models
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Helpers
@using GlobalResources
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.EditDevicePropertiesModel

@{
    ViewBag.Title = @Strings.EditDeviceProperties;
    Layout = "~/Views/Shared/_LayoutNoNavigation.cshtml";
}

<header class="header_main">

    <button class="header_main__button_back" type="button" data-bind="click: backButtonClicked"></button>
    <h2 class="header_main__subhead header_main__subhead--large">@string.Format(Strings.EditDesiredPropertiesFor, Model.DeviceId)</h2>
</header>
<div class="content_outer">

    <div class="content_inner">
        <div id="content">
            <div id="deviceMetadataForm">
                @using (Html.BeginForm("EditDeviceProperties", "Device", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.DeviceId)

                    <fieldset class="edit_form">
                        <table class="values_editor" id="propertiesTable">
                            <thead>
                                <tr class="values_editor__groupheader">
                                    <th class="edit_form__labelHeader">@Strings.ScheduleDesiredPropertyName</th>
                                    <th class="edit_form__labelHeader">@Strings.ScheduleEditValue</th>
                                    <th class="edit_form__labelHeader">@Strings.DataTypeLabel</th>
                                    <th class="edit_form__labelHeader">
                                        <div class="tooltip_header">
                                            @Strings.Delete
                                            <img src="~/Content/img/icon_info_gray.svg" class="details_grid_info tooltip_icon" title="@Strings.EditDesiredPropertyDelete" />
                                        </div>
                                    </th>
                                </tr>
                            </thead>
                            <tbody data-bind="foreach:{data: properties, afterAdd:makeproplist}">
                                <tr class="values_editor__group">
                                    <td>
                                        <input type="text" class="edit_form__texthalf edit_form__propertiesComboBox"
                                               data-msg-regex=" "
                                               data-rule-regex="^desired\.\S+$"
                                               data-rule-maxtwindepth ="5"
                                               data-bind="value: key, disable: isUserDefinedType, css:{edit_form__deleted : isDeleted()},attr:{name: 'propertyName' + $index(), id: 'propertyName' + $index()}" />
                                    </td>
                                    <td>
                                        <input type="text" class="edit_form__texthalf"
                                               data-rule-maxbytelength="512"
                                               data-bind='textInput: value.value, event:{ keyup:$root.updateDataType($data) }, enable:!isDeleted() && key(), css:{edit_form__deleted : isDeleted()}' />
                                    </td>
                                    <td>
                                        <select class="edit_form_select" data-bind="value: dataType,  enable:!isDeleted() && key(), options: $root.twinDataTypeOptions, optionsText: 'text', optionsValue: 'value'"></select>
                                    </td>
                                    <td>
                                        <input type="checkbox"
                                               value="true"
                                               data-bind='checked: isDeleted ,enable: key()' />
                                    </td>
                                    <td><a class="edit_form__link" data-bind="ifnot:$root.oneItemLeft() || isUserDefinedType(), click:$root.remove"><small class="text_small">@Strings.Clear</small></a></td>
                                    <!-- ko with: $root.MatchReportedProp(key) -->
                                    <td data-bind="if:$data != null"><span class="edit_form__labelsmall" data-bind="text:'Reported'"></span></td>
                                    <td data-bind="if:$data != null" style="text-align:left"><span class="edit_form__labelsmall" data-bind="text: value.value()"></span></td>
                                    <!-- /ko -->

                                </tr>
                            </tbody>
                        </table>
                        <div style="clear:both"></div>
                        <a data-bind="click:$root.createEmptyPropertyIfNeeded">
                            <span class="icon-add"></span>
                            <div class="edit_form__labelbutton">
                                @Strings.AddDesiredProperty
                            </div>
                        </a>
                    </fieldset>

                    <fieldset class="fieldset_button">
                        <input type="button" class="button_base button_secondary button_cancel" data-bind="click: backButtonClicked" value="@Strings.Cancel" />
                        <button class="button_base" type="submit">@Strings.SaveChangesToDevice</button>
                    </fieldset>
                }
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    "use strict";

    var resources = {
        redirectUrl: '@Url.Action("Index", "Device")',
        failedToUpdateTwin: '@Html.JavaScriptString(Strings.FailedToUpdateTwin)',
        twinDataType: {
            'string': '@TwinDataType.String',
            'number': '@TwinDataType.Number',
            'boolean': '@TwinDataType.Boolean'
        },
        twinDataTypeOptions: [
            { value: '@TwinDataType.String', text: '@Html.JavaScriptString(Strings.StringLabel)' },
            { value: '@TwinDataType.Number', text: '@Html.JavaScriptString(Strings.NumberLabel)' },
            { value: '@TwinDataType.Boolean', text: '@Html.JavaScriptString(Strings.BooleanLabel)' }
        ]
    }
</script>
<script type="text/javascript" src="~/Scripts/Views/Device/EditDesiredProperties.js?ver=@Constants.JSVersion"></script>
<script type="text/javascript">
    $(document).ready(function () {
        jQuery.validator.addMethod("maxbytelength", function (value, element, params) {
            return this.optional(element) || byteCount(value) <= params
        }, "");
        jQuery.validator.addMethod("maxtwindepth", function (value, element, params) {
            return this.optional(element) || value.match(/\./gi).length <= params
        }, "");
        IoTApp.EditDesiredProperties.init("@Model.DeviceId");
    });


</script>

services/DeviceAdministration/Web/Views/Device/EditDeviceProperties.cshtml
@using System.Globalization
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Helpers
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure.Models
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Helpers
@using GlobalResources
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.EditDevicePropertiesModel

@{
    ViewBag.Title = @Strings.EditDeviceProperties;
    Layout = "~/Views/Shared/_LayoutNoNavigation.cshtml";
}

<header class="header_main">

    <button class="header_main__button_back" type="button"></button>
    <h2 class="header_main__subhead header_main__subhead--large">@string.Format(Strings.EditDevicePropertiesFor, Model.DeviceId)</h2>
</header>
<div class="content_outer"> 

    <div class="content_inner">
        <div id="content">
            <div id="deviceMetadataForm">
                @using (Html.BeginForm("EditDeviceProperties", "Device", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.DeviceId)
                    <p>
                        @Html.ValidationSummary(false)
                    </p>

                    <fieldset class="edit_form">
                        @{
                            DateTime? resolvedTime;
                            for (int i = 0; i < Model.DevicePropertyValueModels.Count; ++i)
                            {
                                if (Model.DevicePropertyValueModels[i] == null)
                                {
                                    continue;
                                }

                                @Html.LabelFor(
                                m => m.DevicePropertyValueModels[i].Value,
                                    Model.DevicePropertyValueModels[i].Name,
                                    new { @class = "edit_form__label" })

                                if (Model.DevicePropertyValueModels[i].IsEditable)
                                {
                                    @Html.TextBoxFor(m => m.DevicePropertyValueModels[i].Value, new { @class = "edit_form__text" })
                                }
                                else
                                {
                                    if ((Model.DevicePropertyValueModels[i].PropertyType == PropertyType.DateTime) &&
                                        (resolvedTime = DynamicValuesHelper.ConvertToDateTime(CultureInfo.InvariantCulture, Model.DevicePropertyValueModels[i].Value)).HasValue)
                                    {
                                        @Html.TextBox(Model.DevicePropertyValueModels[i].Name, resolvedTime.Value.ToString(), new { @readonly = "readonly", @class = "input_text--readonly" })
                                    }
                                    else
                                    {
                                        @Html.TextBoxFor(m => m.DevicePropertyValueModels[i].Value, new { @readonly = "readonly", @class = "input_text--readonly" })
                                    }
                                }

                                @Html.HiddenFor(m => m.DevicePropertyValueModels[i].Name)
                            }
                        }
                    </fieldset>

                    <fieldset class="fieldset_button">
                        <button class="button_base" type="submit">@Strings.SaveChangesToDevice</button>
                    </fieldset>
                            }
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    "use strict";

    var resources = {
        redirectUrl: '@Url.Action("Index", "Device")',
    }
</script>

<script type="text/javascript" src="~/Scripts/Views/Device/EditDeviceProperties.js?ver=@Constants.JSVersion"></script>

services/DeviceAdministration/Web/Views/Device/EditTags.cshtml
@using System.Globalization
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Helpers
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure.Models
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Helpers
@using GlobalResources
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.EditDevicePropertiesModel

@{
    ViewBag.Title = @Strings.EditDeviceProperties;
    Layout = "~/Views/Shared/_LayoutNoNavigation.cshtml";
}

<header class="header_main">

    <button class="header_main__button_back" type="button" data-bind="click: backButtonClicked"></button>
    <h2 class="header_main__subhead header_main__subhead--large">@string.Format(Strings.EditTagsFor, Model.DeviceId)</h2>
</header>
<div class="content_outer">

    <div class="content_inner">
        <div id="content">
            <div id="deviceMetadataForm">
                @using (Html.BeginForm("EditDeviceProperties", "Device", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.DeviceId)

                    <fieldset class="edit_form">
                        <table class="values_editor" id="propertiesTable">
                            <thead>
                                <tr class="values_editor__groupheader">
                                    <th class="edit_form__labelHeader">@Strings.ScheduleChangeTags</th>
                                    <th class="edit_form__labelHeader">@Strings.ScheduleEditValue</th>
                                    <th class="edit_form__labelHeader">@Strings.DataTypeLabel</th>
                                    <th class="edit_form__labelHeader">
                                        <div class="tooltip_header">
                                            @Strings.Delete
                                            <img src="~/Content/img/icon_info_gray.svg" class="details_grid_info tooltip_icon" title="@Strings.EditTagDelete" />
                                        </div>
                                    </th>
                                </tr>
                            </thead>
                            <tbody data-bind="foreach:{data: properties, afterAdd:makeproplist}">
                                <tr class="values_editor__group">
                                    <td>
                                        <input type="text" class="edit_form__texthalf edit_form__propertiesComboBox"
                                               data-msg-regex=" "
                                               data-rule-regex="^tags\.\S+$"
                                               data-rule-maxtwindepth ="5"
                                               data-bind="value: key, disable: isUserDefinedType, css:{edit_form__deleted : isDeleted()}, attr:{name: 'tagName' + $index(), id: 'tagName' + $index()}" />
                                    </td>
                                    <td>
                                        <input type="text" class="edit_form__texthalf"
                                               data-rule-maxbytelength="512"
                                               data-bind='textInput: value.value,event:{ keyup:$root.updateDataType($data) }, enable:!isDeleted() && key(), css:{edit_form__deleted : isDeleted()}' />
                                    </td>
                                    <td>
                                        <select class="edit_form_select" data-bind="value: dataType,  enable:!isDeleted() && key(), options: $root.twinDataTypeOptions, optionsText: 'text', optionsValue: 'value'"></select>
                                    </td>
                                    <td>
                                        <input type="checkbox"
                                               value="true"
                                               data-bind='checked: isDeleted ,enable: key()' />
                                    </td>
                                    <td><a class="edit_form__link" data-bind="ifnot:$root.oneItemLeft() || isUserDefinedType(), click:$root.remove"><small class="text_small">@Strings.Clear</small></a></td>
                                </tr>
                            </tbody>
                        </table>
                        <div style="clear:both"></div>
                        <a data-bind="click:$root.createEmptyPropertyIfNeeded">
                            <span class="icon-add"></span>
                            <div class="edit_form__labelbutton">
                                @Strings.AddTag
                            </div>
                        </a>
                    </fieldset>

                    <fieldset class="fieldset_button">
                        <input type="button" class="button_base button_secondary button_cancel" data-bind="click: backButtonClicked" value="@Strings.Cancel" />
                        <button class="button_base" type="submit">@Strings.SaveChangesToDevice</button>
                    </fieldset>
                }
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    "use strict";

    var resources = {
        redirectUrl: '@Url.Action("Index", "Device")',
        failedToUpdateTwin: '@Html.JavaScriptString(Strings.FailedToUpdateTwin)',
        twinDataType: {
            'string': '@TwinDataType.String',
            'number': '@TwinDataType.Number',
            'boolean': '@TwinDataType.Boolean'
        },
        twinDataTypeOptions: [
            { value: '@TwinDataType.String', text: '@Html.JavaScriptString(Strings.StringLabel)' },
            { value: '@TwinDataType.Number', text: '@Html.JavaScriptString(Strings.NumberLabel)' },
            { value: '@TwinDataType.Boolean', text: '@Html.JavaScriptString(Strings.BooleanLabel)' }
        ]
    }
</script>
<script type="text/javascript" src="~/Scripts/Views/Device/EditTags.js?ver=@Constants.JSVersion"></script>
<script type="text/javascript">

    $(document).ready(function () {
        jQuery.validator.addMethod("maxbytelength", function (value, element, params) {
            return this.optional(element) || byteCount(value) <= params
        }, "");
        jQuery.validator.addMethod("maxtwindepth", function (value, element, params) {
            return this.optional(element) || value.match(/\./gi).length <= params
        }, "");
        IoTApp.EditTags.init("@Model.DeviceId");
    });

</script>

services/DeviceAdministration/Web/Views/Device/RemoveDevice.cshtml
@using GlobalResources
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Helpers
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.RegisteredDeviceModel

@{
    ViewBag.Title = @Strings.RemoveDevice;
    Layout = "~/Views/Shared/_LayoutNoNavigation.cshtml";
}

<header class="header_main">
    <button class="header_main__button_back" type="button"></button>
    <h2 class="header_main__subhead header_main__subhead--large">@String.Format(@Strings.RemoveDeviceFormatted, @Model.DeviceId)</h2>
</header>

<div class="content_outer">

    <div class="content_inner">
        <div id="content">
                @using (Ajax.BeginForm("DeleteDevice", "Device", null,
                    new AjaxOptions()
                    {
                        HttpMethod = "POST",
                        InsertionMode = InsertionMode.Replace,
                        OnFailure = "IoTApp.RemoveDevice.onFailure",
                        OnSuccess = "IoTApp.RemoveDevice.onSuccess",
                        LoadingElementId = "loadingElement"
                    }))
                {
                    @Html.AntiForgeryToken()
                    <div id="removeDeviceContainer">

                        <fieldset class="remove_form">
                            <p class="remove_form__remove_confirmation">@Strings.RemoveDeviceConfirmationPart1</p>
                            <p class="remove_form__remove_confirmation">@Strings.RemoveDeviceConfirmationPart2</p>
                            <div class="remove_checkbox">
                                <input type="checkbox" class="remove_checkbox_check" id="removeDeviceCheckbox" />
                                <label class="remove_checkbox__label" for="removeDeviceCheckbox">@String.Format(@Strings.YesRemoveDeviceFormatted, @Model.DeviceId)</label>
                            </div>
                        </fieldset>

                        <fieldset class="fieldset_button">
                            @Html.HiddenFor(m => m.DeviceId)
                            <button id="removeDevice" disabled="disabled" class="button_base">@Strings.RemoveDeviceConfirmation</button>
                            <button id="cancelButton" type="button" class="button_base button_secondary">@Strings.Cancel</button>
                        </fieldset>
                    </div>
                }

        </div>
    </div>
</div>

<script>
    "use strict";

    var resources = {
        redirectToIndexUrl: '@Url.Action("Index", "Device")',
        errorRemoveDevice: '@Html.JavaScriptString(Strings.ErrorRemoveDevice)'
    };
</script>

<script type="text/javascript" src="~/Scripts/Views/Device/RemoveDevice.js?ver=@Constants.JSVersion"></script>