services/DeviceAdministration/Web/Controllers/DeviceRulesController.cs
using System.Collections.Generic;
using System.Globalization;
using System.Threading.Tasks;
using System.Web.Mvc;
using GlobalResources;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.Common.Models;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure.BusinessLogic;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure.Models;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models;
using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Security;
using Newtonsoft.Json;

namespace Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Controllers
{
    public class DeviceRulesController : Controller
    {
        private readonly IDeviceRulesLogic _deviceRulesLogic;

        public DeviceRulesController(IDeviceRulesLogic deviceRulesLogic)
        {
            this._deviceRulesLogic = deviceRulesLogic;
        }

        [RequirePermission(Permission.ViewRules)]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Return a view for the right panel on the DeviceRules index screen
        /// </summary>
        /// <param name="deviceId"></param>
        /// <param name="ruleId"></param>
        /// <returns></returns>
        [HttpGet]
        [RequirePermission(Permission.ViewRules)]
        public async Task<ActionResult> GetRuleProperties(string deviceId, string ruleId)
        {
            DeviceRule rule = await _deviceRulesLogic.GetDeviceRuleAsync(deviceId, ruleId);
            EditDeviceRuleModel editModel = CreateEditModelFromDeviceRule(rule);
            return PartialView("_DeviceRuleProperties", editModel);
        }

        /// <summary>
        /// Update rule properties. This method returns json with either a success = true or an error = errorMessage
        /// After calling this method the user should update the UI by explicitly retrieving fresh data in
        /// a subsequent call
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [RequirePermission(Permission.EditRules)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UpdateRuleProperties(EditDeviceRuleModel model)
        {
            string errorMessage = model.CheckForErrorMessage();
            if(!string.IsNullOrWhiteSpace(errorMessage))
            {
                return Json(new { error = errorMessage });
            }

            DeviceRule rule = CreateDeviceRuleFromEditModel(model);
            TableStorageResponse<DeviceRule> response = await _deviceRulesLogic.SaveDeviceRuleAsync(rule);

            return BuildRuleUpdateResponse(response);
        }

        /// <summary>
        /// Get a new rule with bare-bones data to be used in creating a new rule for a device
        /// </summary>
        /// <param name="deviceId"></param>
        /// <returns></returns>
        [HttpGet]
        [RequirePermission(Permission.EditRules)]
        public async Task<ActionResult> GetNewRule(string deviceId)
        {
            DeviceRule rule = await _deviceRulesLogic.GetNewRuleAsync(deviceId);
            return Json(rule);
        }

        /// <summary>
        /// Update the enabled state for a rule. No other properties will be updated on the rule, 
        /// even if they are included in the device rule model. This method return json with either 
        /// success = true or error = errorMessage. If the user wants to update the ui with fresh
        /// data subsequent explicit calls should be made for new data
        /// </summary>
        /// <param name="ruleModel"></param>
        /// <returns></returns>
        [HttpPost]
        [RequirePermission(Permission.EditRules)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UpdateRuleEnabledState(EditDeviceRuleModel ruleModel)
        {
            TableStorageResponse<DeviceRule> response = await _deviceRulesLogic.UpdateDeviceRuleEnabledStateAsync(
                ruleModel.DeviceID, 
                ruleModel.RuleId, 
                ruleModel.EnabledState);

            return BuildRuleUpdateResponse(response);
        }

        /// <summary>
        /// Delete the given rule for a device
        /// </summary>
        /// <param name="ruleModel"></param>
        /// <returns></returns>
        [HttpDelete]
        [RequirePermission(Permission.DeleteRules)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteDeviceRule(string deviceId, string ruleId)
        {
            TableStorageResponse<DeviceRule> response = await _deviceRulesLogic.DeleteDeviceRuleAsync(deviceId, ruleId);

            return BuildRuleUpdateResponse(response);
        }

        private JsonResult BuildRuleUpdateResponse(TableStorageResponse<DeviceRule> response)
        {
            switch (response.Status)
            {
                case TableStorageResponseStatus.Successful:
                    return Json(new 
                    { 
                        success = true
                    });
                case TableStorageResponseStatus.ConflictError:
                    return Json(new
                    {
                        error = Strings.TableDataSaveConflictErrorMessage,
                        entity = JsonConvert.SerializeObject(response.Entity)
                    });
                case TableStorageResponseStatus.DuplicateInsert:
                    return Json(new
                    {
                        error = Strings.RuleAlreadyAddedError,
                        entity = JsonConvert.SerializeObject(response.Entity)
                    });
                case TableStorageResponseStatus.NotFound:
                    return Json(new
                    {
                        error = Strings.UnableToRetrieveRuleFromService,
                        entity = JsonConvert.SerializeObject(response.Entity)
                    });
                case TableStorageResponseStatus.UnknownError:
                default:
                    return Json(new
                    {
                        error = Strings.RuleUpdateError,
                        entity = JsonConvert.SerializeObject(response.Entity)
                    });
            }
        }

        /// <summary>
        /// Navigate to the EditRuleProperties screen
        /// </summary>
        /// <param name="deviceId"></param>
        /// <param name="ruleId"></param>
        /// <returns></returns>
        [RequirePermission(Permission.EditRules)]
        public async Task<ActionResult> EditRuleProperties(string deviceId, string ruleId)
        {
            EditDeviceRuleModel editModel = null;
            //empty ruleId implies that we are creating new
            if (string.IsNullOrWhiteSpace(ruleId))
            {
                bool canCreate = await _deviceRulesLogic.CanNewRuleBeCreatedForDeviceAsync(deviceId);
                if (!canCreate)
                {
                    editModel = new EditDeviceRuleModel()
                    {
                        DeviceID = deviceId
                    };
                    return View("AllRulesAssigned", editModel);
                }
            }

            DeviceRule ruleModel = await _deviceRulesLogic.GetDeviceRuleOrDefaultAsync(deviceId, ruleId);
            Dictionary<string, List<string>> availableFields = await _deviceRulesLogic.GetAvailableFieldsForDeviceRuleAsync(ruleModel.DeviceID, ruleModel.RuleId);

            List<SelectListItem> availableDataFields = this.ConvertStringListToSelectList(availableFields["availableDataFields"]);
            List<SelectListItem> availableOperators = this.ConvertStringListToSelectList(availableFields["availableOperators"]);
            List<SelectListItem> availableRuleOutputs = this.ConvertStringListToSelectList(availableFields["availableRuleOutputs"]);

            editModel = CreateEditModelFromDeviceRule(ruleModel);
            editModel.AvailableDataFields = availableDataFields;
            editModel.AvailableOperators = availableOperators;
            editModel.AvailableRuleOutputs = availableRuleOutputs;

            return View("EditDeviceRuleProperties", editModel);
        }

        /// <summary>
        /// Navigate to the DeleteRuleProperties screen
        /// </summary>
        /// <param name="deviceId"></param>
        /// <param name="ruleId"></param>
        /// <returns></returns>
        [RequirePermission(Permission.DeleteRules)]
        public async Task<ActionResult> RemoveRule(string deviceId, string ruleId)
        {
            DeviceRule ruleModel = await _deviceRulesLogic.GetDeviceRuleOrDefaultAsync(deviceId, ruleId);
            EditDeviceRuleModel editModel = CreateEditModelFromDeviceRule(ruleModel);
            return View("RemoveDeviceRule", editModel);
        }

        private DeviceRule CreateDeviceRuleFromEditModel(EditDeviceRuleModel editModel)
        {
            DeviceRule rule = new DeviceRule(editModel.RuleId);
            rule.DataField = editModel.DataField;
            rule.DeviceID = editModel.DeviceID;
            rule.EnabledState = editModel.EnabledState;
            rule.Etag = editModel.Etag;
            rule.Operator = editModel.Operator;
            rule.RuleOutput = editModel.RuleOutput;
            if (!string.IsNullOrWhiteSpace(editModel.Threshold))
            {
                rule.Threshold =
                    double.Parse(
                        editModel.Threshold,
                        NumberStyles.Float,
                        CultureInfo.CurrentCulture);
            }

            return rule;
        }

        private EditDeviceRuleModel CreateEditModelFromDeviceRule(DeviceRule rule)
        {
            EditDeviceRuleModel editModel = new EditDeviceRuleModel();
            editModel.RuleId = rule.RuleId;
            editModel.DataField = rule.DataField;

services/DeviceAdministration/Web/Views/DeviceRules/AllRulesAssigned.cshtml
@using GlobalResources
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.EditDeviceRuleModel
@{
    ViewBag.Title = "Edit Device Rule Properties";
    Layout = "~/Views/Shared/_LayoutNoNavigation.cshtml";
}

<header class="header_main">

    <button class="header_main__button_back" type="button"></button>
    <h2 class="header_main__subhead header_main__subhead--large">@string.Format(Strings.EditDeviceRuleFormatted, Strings.Create, Model.DeviceID)</h2>

</header>

<div class="content_outer">
    <div class="content_inner">
        <div id="content">
            <div id="deviceRuleMetadataForm">
                <p class="grid_detail_value">@Strings.DeviceRulesFullError</p>
                <button class="button_base view_rules_button" id="view_rules_button">@Strings.ViewRules</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    "use strict";

    var resources = {
        redirectUrl: '@Url.Action("Index", "DeviceRules")'
    }
</script>

<script type="text/javascript" src="~/Scripts/Views/DeviceRules/AllRulesAssigned.js?ver=@Constants.JSVersion"></script>

services/DeviceAdministration/Web/Views/DeviceRules/EditDeviceRuleProperties.cshtml
@using System.Web.Mvc.Html
@using GlobalResources
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Helpers
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.EditDeviceRuleModel

@{
    ViewBag.Title = "Edit Device Rule Properties";
    Layout = "~/Views/Shared/_LayoutNoNavigation.cshtml";
}

<header class="header_main">

    <button class="header_main__button_back" type="button"></button>
    @{ string firstString = @Strings.Edit; }
    @{if(!string.IsNullOrWhiteSpace(Request.Params["createRule"]))
    {
    firstString = @Strings.Create;
    }}
    <h2 class="header_main__subhead header_main__subhead--large">@string.Format(Strings.EditDeviceRuleFormatted, firstString, Model.DeviceID)</h2>
</header>
<div class="content_outer">
    <div class="content_inner">
        <div id="content">
            <div id="deviceRuleMetadataForm">
                @using (Ajax.BeginForm("UpdateRuleProperties", "DeviceRules", null,
        new AjaxOptions()
        {
            HttpMethod = "POST",
            OnBegin = "IoTApp.EditDeviceRuleProperties.onBegin",
            OnFailure = "IoTApp.EditDeviceRuleProperties.onFailure",
            OnSuccess = "IoTApp.EditDeviceRuleProperties.onSuccess",
            OnComplete = "IoTApp.EditDeviceRuleProperties.onComplete",
            LoadingElementId = "loadingElement"            
        }, null))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.Etag)
                    @Html.HiddenFor(m => m.RuleId)
                    @Html.HiddenFor(m => m.EnabledState)
                    @Html.HiddenFor(m => m.DeviceID)

    <fieldset class="edit_form">
        @{ string state = @Strings.Enabled; }
        @{if (!Model.EnabledState)
        {
            state = @Strings.Disabled;
        }
        }
        <label class="edit_form__label">@Strings.RuleStatus</label>
        @Html.TextBoxFor(m => state, new { @readonly = "readonly", @class = "input_text--readonly" })

        <label class="edit_form__label">@Strings.DataFieldHeader</label>
        @Html.DropDownListFor(m => m.DataField, Model.AvailableDataFields, new { @class = "edit_form__select" })

        <label class="edit_form__label">@Strings.OperatorHeader</label>
        @Html.HiddenFor(m => m.Operator)
        <p class="edit_form__edit_rule_value_display">@Model.Operator</p>

        <label class="edit_form__label">@Strings.ThresholdHeader</label>
        @Html.TextBoxFor(m => m.Threshold, new { @Title = Strings.DoubleCommandHint, @class = "edit_form__text" })

        <label class="edit_form__label">@Strings.RuleOutputHeader</label>
        @{
            object htmlAttributes = new { @class = "edit_form__select edit_form_control_last" };
            if (Model.AvailableRuleOutputs.Count < 2)
            {
                htmlAttributes = new { @disabled = "disabled", @class = "edit_form__select edit_form_control_last" };
                @Html.HiddenFor(m => m.RuleOutput);
            }
        }
        @Html.DropDownListFor(m => m.RuleOutput, Model.AvailableRuleOutputs, htmlAttributes)
    </fieldset>

                    <fieldset class="fieldset_button">
                        <button class="button_base update_rule_properties" type="submit">@Strings.SaveAndViewRules</button>
                    </fieldset>
                }
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    "use strict";

    var resources = {
        redirectUrl: '@Url.Action("Index", "DeviceRules")',
        ruleUpdateError: '@Html.JavaScriptString(Strings.RuleUpdateError)',
        enabledString: '@Html.JavaScriptString(Strings.Enabled)',
        disabledString: '@Html.JavaScriptString(Strings.Disabled)'
    }
</script>

<script type="text/javascript" src="~/Scripts/Views/DeviceRules/EditDeviceRuleProperties.js?ver=@Constants.JSVersion"></script>

services/DeviceAdministration/Web/Views/DeviceRules/Index.cshtml
@using GlobalResources
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Helpers
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.EditDeviceRuleModel

@{
    ViewBag.Title = @Strings.DeviceRules;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<noscript>
    <div class="error_noscript">
        <h1 class="error_noscript__header">@Strings.NoscriptHeader</h1>
        <p>@Strings.NoscriptP1</p>
        <p>@Strings.NoscriptP2</p>
    </div>
</noscript>


<div class="content_outer content_outer--background_color content_grid">

    <div class="content_inner content_inner--inherit_max_width_no_margin">

        <div class="grid_container height_fixed">

            @*Datatables plugin for jQuery. www.datatables.net*@
            <table id="ruleTable" class="order-column">

                <thead>
                    <tr>
                        <th>@Strings.StatusHeader</th>
                        <th>@Strings.RuleIdHeader</th>
                        <th>@Strings.DeviceIdHeader</th>
                        <th>@Strings.DataFieldHeader</th>
                        <th>@Strings.OperatorHeader</th>
                        <th>@Strings.ThresholdHeader</th>
                        <th>@Strings.RuleOutputHeader</th>
                    </tr>
                </thead>

                <tbody></tbody>

            </table>
        </div>

        <div class="details_grid_closed height_fixed button_details_grid">
            <h2 class="details_grid_closed__grid_subhead">@Strings.RulePropertiesPaneLabel</h2>
        </div>

        <div class="details_grid height_fixed">

            <h2 class="details_grid__grid_subhead button_details_grid">@Strings.Properties</h2>

            <div id="details_grid_container">
                <div class="details_grid__no_selection">
                    @Strings.NoRuleSelectedLabel
                </div>
            </div>

            <div id="loadingElement" class="loader_container loader_container_details">
                <div class="loader_container__loader"></div>
            </div>

        </div>

    </div>

</div>


<script>
    "use strict";

    var resources = {
        retry: '@Html.JavaScriptString(Strings.Retry)',
        serviceUnavailable: '@Html.JavaScriptString(Strings.ServiceUnavailable)',
        unableToRetrieveRuleFromService: '@Html.JavaScriptString(Strings.UnableToRetrieveRuleFromService)',
        disabled: '@Html.JavaScriptString(Strings.Disabled)',
        enabled: '@Html.JavaScriptString(Strings.Enabled)',
        failedToRetrieveRules: '@Html.JavaScriptString(Strings.FailedToRetrieveRules)',
        noRuleSelected: '@Html.JavaScriptString(Strings.NoRuleSelectedLabel)',
        ruleUpdateError: '@Html.JavaScriptString(Strings.RuleUpdateError)',
        rulesList: '@Html.JavaScriptString(Strings.Rules)',
        nextPage: '@Html.JavaScriptString(Strings.Next)',
        previousPage: '@Html.JavaScriptString(Strings.Previous)'
    };
</script>

<script src="~/Scripts/jquery-datatables-api-extensions.js"></script>
<script src="~/Scripts/Views/DeviceRules/DeviceRulesIndex.js?ver=@Constants.JSVersion"></script>
<script src="~/Scripts/Views/DeviceRules/DeviceRuleProperties.js?ver=@Constants.JSVersion"></script>

services/DeviceAdministration/Web/Views/DeviceRules/RemoveDeviceRule.cshtml
@using GlobalResources
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Helpers
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.EditDeviceRuleModel

@{
    ViewBag.Title = @Strings.RemoveRule;
    Layout = "~/Views/Shared/_LayoutNoNavigation.cshtml";
}

<header class="header_main">
    <button class="header_main__button_back" type="button"></button>
    <h2 class="header_main__subhead header_main__subhead--large">@String.Format(@Strings.RemoveRuleFormatted, @Model.DataField, @Model.DeviceID)</h2>
</header>

<div class="content_outer">

    <div class="content_inner">
        <div id="content">
            @using (Ajax.BeginForm("DeleteDeviceRule", "DeviceRules", null,
                    new AjaxOptions()
                    {
                        HttpMethod = "DELETE",
                        OnFailure = "IoTApp.RemoveDeviceRule.onFailure",
                        OnSuccess = "IoTApp.RemoveDeviceRule.onSuccess",
                        LoadingElementId = "loadingElement"
                    }))
            {
                @Html.AntiForgeryToken()
                <div id="removeRuleContainer">

                    <fieldset class="remove_form">
                        <p class="remove_form__remove_confirmation">@Strings.RemoveRuleConfirmationPart1</p>
                        <p class="remove_form__remove_confirmation">@Strings.RemoveRuleConfirmationPart2</p>
                        <div class="remove_checkbox">
                            <input type="checkbox" class="remove_checkbox_check" id="removeRuleCheckbox" />
                            <label class="remove_checkbox__label" for="removeRuleCheckbox">@String.Format(@Strings.YesRemoveRuleFormatted, @Model.DataField, @Model.DeviceID)</label>
                        </div>
                    </fieldset>

                    <fieldset class="fieldset_button">
                        @Html.HiddenFor(m => m.DeviceID)
                        @Html.HiddenFor(m => m.RuleId)
                        <button id="removeRule" disabled="disabled" class="button_base">@Strings.RemoveRule</button>
                        <button id="cancelButton" type="button" class="button_base button_secondary">@Strings.Cancel</button>
                    </fieldset>
                </div>
            }

        </div>
    </div>
</div>

<script>
    "use strict";

    var resources = {
        redirectToIndexUrl: '@Url.Action("Index", "DeviceRules")',
        errorRemoveRule: '@Html.JavaScriptString(Strings.ErrorRemoveRule)'
    };
</script>

<script type="text/javascript" src="~/Scripts/Views/DeviceRules/RemoveDeviceRule.js?ver=@Constants.JSVersion"></script>

services/DeviceAdministration/Web/Views/DeviceRules/_DeviceRuleProperties.cshtml
@using System.Web.Mvc.Html
@using Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Security
@using GlobalResources
@model Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Web.Models.EditDeviceRuleModel

<div class="header_grid header_grid_general">
    <h3 class="grid_subheadhead_detail">@Strings.DeviceProperties</h3>
</div>

<section class="details_grid_general" id="deviceDetailsGrid">
    <h4 class="grid_subhead_detail_label">@Strings.DeviceId</h4>
    <p class="grid_detail_value" name="deviceField_deviceId">@Model.DeviceID</p>
</section>

<div class="header_grid header_grid_general">
    <h3 class="grid_subheadhead_detail">@Strings.RuleStatus</h3>
</div>

@{if (PermsChecker.HasPermission(Permission.EditRules))
{
    using (Ajax.BeginForm("UpdateRuleEnabledState", "DeviceRules", null,
    new AjaxOptions()
    {
        HttpMethod = "POST",
        OnBegin = "IoTApp.DeviceRuleProperties.onBegin",
        OnFailure = "IoTApp.DeviceRuleProperties.onFailure",
        OnSuccess = "IoTApp.DeviceRuleProperties.onSuccess",
        OnComplete = "IoTApp.DeviceRuleProperties.onComplete",
        LoadingElementId = "loadingElement"
    }, null))
    {

        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.DeviceID)
        @Html.HiddenFor(m => m.DataField)
        @Html.HiddenFor(m => m.RuleId)
        @Html.HiddenFor(m => m.EnabledState, new { @Value = !Model.EnabledState })
    <section class="grid_rules_details" id="ruleStatusGrid">
        <div class="grid_rules_details__rule_status_container">
            @{if (Model.EnabledState)
            {
                <button type="submit" class="button_base rule_status_container___rule_status_button" id="rule_status_enabled">
                    @Strings.DisableRule
                </button>
            }
            else
            {
                <button type="submit" class="button_base rule_status_container___rule_status_button" id="rule_status_disabled">
                    @Strings.EnableRule
                </button>

                if (PermsChecker.HasPermission(Permission.DeleteRules))
                {
                    <button type="button" class="button_base rule_status_container___rule_status_button" id="remove_rule_button">
                        @Strings.RemoveRuleButtonLabel
                    </button>
                }
            }
}
        </div>
    </section>
    }
}
  else
  {
    <section class="details_grid_general" id="deviceDetailsGrid">
        <p class="grid_detail_value" name="ruleField_enabledState">
            @{if (Model.EnabledState)
            {
                @Strings.Enabled;
            }
            else
            {
                @Strings.Disabled;
            }
            }
        </p>
    </section>
}
}

<div class="header_grid header_grid_general">
    <h3 class="grid_subheadhead_detail">@Strings.RuleProperties</h3>
    @if (PermsChecker.HasPermission(Permission.EditRules))
    {
        @Html.ActionLink(@Strings.Edit, "EditRuleProperties", "DeviceRules",
            new { deviceId = Model.DeviceID, ruleId = Model.RuleId },
            new { id = "edit_metadata_link", @class = "link_grid_subheadhead_detail" })
    }
</div>

<section class="details_grid_general" id="rulePropertiesGrid">
    <h4 class="grid_subhead_detail_label">@Strings.DataFieldHeader</h4>
    <p class=" grid_detail_value" name="deviceField_@Model.DataField">@Model.DataField</p>

    <h4 class="grid_subhead_detail_label">@Strings.OperatorHeader</h4>
    <p class=" grid_detail_value" name="deviceField_@Model.Operator">@Model.Operator</p>

    <h4 class="grid_subhead_detail_label">@Strings.ThresholdHeader</h4>
    <p class=" grid_detail_value" name="deviceField_@Model.Threshold">@Model.Threshold</p>

    <h4 class="grid_subhead_detail_label">@Strings.RuleOutputHeader</h4>
    <p class=" grid_detail_value" name="deviceField_@Model.RuleOutput">@Model.RuleOutput</p>
</section>